openapi: 3.0.2
info:
  title: Newspaper openapi-schema
  version: 1.0.0
paths:
  /api/news/:
    get:
      operationId: listNews
      description: List paginated news
      parameters:
      - name: limit
        required: false
        in: query
        description: Number of results to return per page
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results
        schema:
          type: integer
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 123
                  next:
                    type: string
                    nullable: true
                    format: uri
                    example: http://newspaper.org/api/news/?offset=0&limit=10
                  previous:
                    type: string
                    nullable: true
                    format: uri
                    example: http://newspaper.org/api/news/?offset=0&limit=10
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/News'
      tags:
      - news
    post:
      operationId: createNews
      description: Create news
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateNews'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CreateNews'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CreateNews'
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/News'
      tags:
        - news
  /api/news/{id}/:
    get:
      operationId: retrieveNews
      description: 'Retrieve specific news'
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this news
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/News'
      tags:
      - news
    put:
      operationId: updateNews
      description: Update specific news
      parameters:
        - name: id
          in: path
          required: true
          description: A unique integer value identifying this news
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateNews'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UpdateNews'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UpdateNews'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateNews'
      tags:
        - news
    patch:
      operationId: partialUpdateNews
      description: Partial update specific news
      parameters:
        - name: id
          in: path
          required: true
          description: A unique integer value identifying this news
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateNews'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UpdateNews'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UpdateNews'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateNews'
      tags:
        - news
    delete:
      operationId: deleteNews
      description: Delete specific news
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this news
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - news
  /api/articles/:
    get:
      operationId: listArticles
      description: List paginated articles
      parameters:
        - name: limit
          required: false
          in: query
          description: Number of results to return per page
          schema:
            type: integer
        - name: offset
          required: false
          in: query
          description: The initial index from which to return the results
          schema:
            type: integer
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 123
                  next:
                    type: string
                    nullable: true
                    format: uri
                    example: http://newspaper.org/api/articles/?offset=0&limit=10
                  previous:
                    type: string
                    nullable: true
                    format: uri
                    example: http://newspaper.org/api/articles/?offset=0&limit=10
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/Article'
      tags:
        - articles
    post:
      operationId: createArticle
      description: Create article
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateArticle'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CreateArticle'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CreateArticle'
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Article'
      tags:
        - articles
  /api/articles/{id}/:
    get:
      operationId: retrieveArticle
      description: 'Retrieve specific article'
      parameters:
        - name: id
          in: path
          required: true
          description: A unique integer value identifying this article
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Article'
      tags:
        - articles
    put:
      operationId: updateArticle
      description: Update specific article
      parameters:
        - name: id
          in: path
          required: true
          description: A unique integer value identifying this article
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateArticle'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UpdateArticle'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UpdateArticle'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateArticle'
      tags:
        - articles
    patch:
      operationId: partialUpdateArticle
      description: Partial update specific article
      parameters:
        - name: id
          in: path
          required: true
          description: A unique integer value identifying this article
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateArticle'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UpdateArticle'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UpdateArticle'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateArticle'
      tags:
        - articles
    delete:
      operationId: deleteArticle
      description: 'Delete specific article'
      parameters:
        - name: id
          in: path
          required: true
          description: A unique integer value identifying this article
          schema:
            type: string
      responses:
        '204':
          description: ''
      tags:
        - articles
components:
  schemas:
    News:
      type: object
      properties:
        url:
          type: string
        id:
          type: integer
        title:
          type: string
        content:
          type: string
        rating:
          type: integer
        author:
          type: string
        dt_created:
          type: string
        categories:
          type: array
    CreateNews:
      type: object
      properties:
        title:
          type: string
        content:
          type: string
    UpdateNews:
      type: object
      properties:
        title:
          type: string
        content:
          type: string
    Article:
      type: object
      properties:
        url:
          type: string
        id:
          type: integer
        title:
          type: string
        content:
          type: string
        rating:
          type: integer
        author:
          type: string
        dt_created:
          type: string
        categories:
          type: array
    CreateArticle:
      type: object
      properties:
        title:
          type: string
        content:
          type: string
    UpdateArticle:
      type: object
      properties:
        title:
          type: string
        content:
          type: string
