openapi: 3.0.2
info:
  title: 'Newspaper'
  version: '1.0.0'
paths:
  /news/:
    get:
      operationId: listNews
      description: 'List news'
      parameters:
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 123
                  next:
                    type: string
                    nullable: true
                    format: uri
                    example: http://newspaper.org/news/?offset=0&limit=10
                  previous:
                    type: string
                    nullable: true
                    format: uri
                    example: http://newspaper.org/news/?offset=0&limit=10
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/News'
          description: ''
      tags:
      - news
  /news/create/:
    post:
      operationId: createNews
      description: 'Create news'
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateNews'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CreateNews'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CreateNews'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateNews'
          description: ''
      tags:
      - news
  /news/{id}/:
    get:
      operationId: retrieveNews
      description: 'Retrieve specific news'
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this News.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/News'
          description: ''
      tags:
      - news
  /news/{id}/edit/:
    patch:
      operationId: EditNews
      description: 'Edit specific news'
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this News.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EditNews'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/EditNews'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/EditNews'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EditNews'
          description: ''
      tags:
      - news
  /news/{id}/delete/:
    delete:
      operationId: destroyNews
      description: 'Delete specific news'
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this News.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - news
  /articles/:
    get:
      operationId: listArticles
      description: 'List articles'
      parameters:
        - name: limit
          required: false
          in: query
          description: Number of results to return per page.
          schema:
            type: integer
        - name: offset
          required: false
          in: query
          description: The initial index from which to return the results.
          schema:
            type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 123
                  next:
                    type: string
                    nullable: true
                    format: uri
                    example: http://newspaper.org/articles/?offset=0&limit=10
                  previous:
                    type: string
                    nullable: true
                    format: uri
                    example: http://newspaper.org/articles/?offset=0&limit=10
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/Articles'
          description: ''
      tags:
        - articles
  /article/create/:
    post:
      operationId: createArticle
      description: 'Create article'
      parameters: [ ]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateArticle'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CreateArticle'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CreateArticle'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateArticle'
          description: ''
      tags:
        - articles
  /article/{id}/:
    get:
      operationId: retrieveArticle
      description: 'Retrieve specific article'
      parameters:
        - name: id
          in: path
          required: true
          description: A unique integer value identifying this News.
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Article'
          description: ''
      tags:
        - articles
  /article/{id}/edit/:
    patch:
      operationId: EditArticle
      description: 'Edit specific article'
      parameters:
        - name: id
          in: path
          required: true
          description: A unique integer value identifying this News.
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EditArticle'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/EditArticle'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/EditArticle'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EditArticle'
          description: ''
      tags:
        - articles
  /article/{id}/delete/:
    delete:
      operationId: destroyArticle
      description: 'Delete specific article'
      parameters:
        - name: id
          in: path
          required: true
          description: A unique integer value identifying this News.
          schema:
            type: string
      responses:
        '204':
          description: ''
      tags:
        - articles
components:
  schemas:
    News:
      type: object
      properties:
        title:
          type: string
        content:
          type: string
        rating:
          type: integer
        dt_created:
          type: string
    CreateNews:
      type: object
      properties:
        title:
          type: string
        content:
          type: string
        categories:
          type: integer
    EditNews:
      type: object
      properties:
        title:
          type: string
        content:
          type: string
        categories:
          type: integer
        rating:
          type: integer
    Article:
      type: object
      properties:
        title:
          type: string
        content:
          type: string
        rating:
          type: integer
        dt_created:
          type: string
    CreateArticle:
      type: object
      properties:
        title:
          type: string
        content:
          type: string
        categories:
          type: integer
    EditArticle:
      type: object
      properties:
        title:
          type: string
        content:
          type: string
        categories:
          type: integer
        rating:
          type: integer
